const techs = [
    {
        id: '1',
        name: 'Scratch',
        image_url: '/images/scratch.png',
        image_alt: 'image of Scratch',
        desc: 'Create animations, apps, and educational stories by adding code, images, and sounds.',
        width: 500,
        height: 500,
        bg: '#FFA500',
    },
    {
        id: '2',
        name: 'Python',
        image_url: '/images/python.png',
        image_alt: 'image of Python',
        desc: 'Make digital art, games, and new web applications while learning one of the world\'s most popular programming languages.',
        width: 500,
        height: 500,
        bg: '#ADD8E6',
    },
    {
        id: '3',
        name: 'Web',
        image_url: '/images/web.png',
        image_alt: 'image of Web',
        desc: 'Build websites and apps by learning HTML, CSS, and JavaScript.',
        width: 500,
        height: 500,
        bg: '#90EE90',
    },
    {
        id: '4',
        name: 'Logo',
        image_url: '/images/code_club_logo.jpg',    
        image_alt: 'image of Logo',
        width: 50,
        height: 50,
    },
    {
        id: '5',
        name: 'Learn to code with Code Club',
        desc: 'Our projects have step-by-step instructions to teach you how to create games, animations, and much more. Choose from hundreds of options, in up to 30 languages.',
        bg: '#00FFFF',
    },
    {
        id: '6',
        name: 'Introduction to Scratch sprites, scripts and loops',
        image_url: '/images/scratch-intro.webp',
        image_alt: 'image of Scratch intro',
        desc: 'In this introduction to coding in Scratch for beginners, you will learn how to add code, costumes, and sounds to sprites as you make animations, a game, an app, and a book',
        width: 500,
        height: 500,
        bg: '#FFA500',
    },
    {
        id: '7',
        name: 'More Scratch broadcast,decision and variables',
        image_url: '/images/more-scratch.webp',
        image_alt: 'image of more Scratch',
        desc: 'More Scratch moves beyond the basics introduced in Introduction to Scratch. You will make apps, games,and simulations using messages broadcasting, if..then, and if.. then...else decisions and variables',
        width: 500,
        height: 500,
        bg: '#ADD8E6',
    },  
    {
        id: '8',
        name: 'Further Scratch clones, my blocks, and Boolean Logic',
        image_url: '/images/further-scratch.webp',
        image_alt: 'image of further Scratch',
        desc: 'Further Scratch moves beyond the skills introduced in Introductions to Scratch and More Scratch. You will make apps,games,computer- generated art, and simulations using Boolean Logc, functions, clones, and more',
        width: 500,
        height: 500,
        bg: '#FFA500',
    },
    {
        id: '9',
        name: 'Introduction to Python variables, functions, and loops',
        image_url: '/images/python-intro.webp',
        image_alt: 'image of Python intro',
        width: 500,
        height: 500,
        bg: '#FFA500',
    },
    {
        id: '10',
        name: 'More Python lists, dictionaries, and data',
        image_url: '/images/more-python.webp',
        image_alt: 'image of Python more',
        desc: 'More Python moves beyond the basics introduced in Introduction to Python. You will learn how to use lists, dictionaries, and files to create charts, models and artwork',
        width: 500,
        height: 500,
        bg: '#ADD8E6',
    },
    {
        id: '11',
        name: 'Introduction to Web HTML, CSS, and animations',
        image_url: '/images/web-intro.webp',
        image_alt: 'image of Web intro',
        desc: 'In this introduction to Web Design for beginners, you will learn how to add structure and style webpages with images, lists, fonts, quotes, links and animation.',
        width: 500,
        height: 500,
        bg: '#FFA500',
    },
    {
        id: '12',
        name: 'More Web HTML, CSS, and JavaScript',
        image_url: '/images/more-web.webp',
        image_alt: 'image of Web more',
        desc: 'More Web moves beyond the basics introduced in Introduction to Web. Modern Web Design has turned websites from static and boring walls of information into ways of providing fun and engaging experiences to a user. Take users on a journey and transport them to somewhere completely new!',
        width: 500,
        height: 500,
        bg: '#ADD8E6',
    },
    {
        id: '13',
        name: 'Scratch',
        desc: 'Begin your adventure in digital making, by learning to code animations, stories, and games in Scratch...',
        bg: '#00FFFF',
    },
    {
        id: '14',
        name: 'Python',
        desc: 'Learn about Python, one of the world\'s most popularprogramming languages to create digital art, interactive maps andmodels.',
        bg: '#00FFFF',
    },
    {
        id: '15',
        name: 'Web',
        desc: 'Begin your adventure in digital making, by learning to code animations, stories, and games in Scratch...',
        bg: '#00FFFF',
    },

];

export {techs};